// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(OfficeMonitorContext))]
    partial class OfficeMonitorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeviceId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ResolvedAt", "TriggeredAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("DAL.Entities.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RatedPowerWatts")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fan 1",
                            RatedPowerWatts = 60,
                            RoomId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fan 2",
                            RatedPowerWatts = 60,
                            RoomId = 1,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Light 1",
                            RatedPowerWatts = 15,
                            RoomId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Light 2",
                            RatedPowerWatts = 15,
                            RoomId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            Name = "Light 3",
                            RatedPowerWatts = 15,
                            RoomId = 1,
                            Type = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Fan 1",
                            RatedPowerWatts = 60,
                            RoomId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fan 2",
                            RatedPowerWatts = 60,
                            RoomId = 2,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Light 1",
                            RatedPowerWatts = 15,
                            RoomId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Light 2",
                            RatedPowerWatts = 15,
                            RoomId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Light 3",
                            RatedPowerWatts = 15,
                            RoomId = 2,
                            Type = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "Fan 1",
                            RatedPowerWatts = 60,
                            RoomId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Fan 2",
                            RatedPowerWatts = 60,
                            RoomId = 3,
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Light 1",
                            RatedPowerWatts = 15,
                            RoomId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Light 2",
                            RatedPowerWatts = 15,
                            RoomId = 3,
                            Type = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Light 3",
                            RatedPowerWatts = 15,
                            RoomId = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.DeviceState", b =>
                {
                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastChangedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DeviceId");

                    b.ToTable("DeviceStates");

                    b.HasData(
                        new
                        {
                            DeviceId = 1,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 2,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 3,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 4,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 5,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 6,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 7,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 8,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 9,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 10,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 11,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 12,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 13,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 14,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            DeviceId = 15,
                            IsOn = false,
                            LastChangedAt = new DateTime(2026, 1, 1, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("DAL.Entities.DeviceStateHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOn")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId", "ChangedAt");

                    b.ToTable("DeviceStateHistories");
                });

            modelBuilder.Entity("DAL.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "drawing",
                            Name = "Drawing Room",
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "work1",
                            Name = "Work Room 1",
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "work2",
                            Name = "Work Room 2",
                            Type = 2
                        });
                });

            modelBuilder.Entity("DAL.Entities.Alert", b =>
                {
                    b.HasOne("DAL.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DAL.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DAL.Entities.Device", b =>
                {
                    b.HasOne("DAL.Entities.Room", "Room")
                        .WithMany("Devices")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DAL.Entities.DeviceState", b =>
                {
                    b.HasOne("DAL.Entities.Device", "Device")
                        .WithOne("DeviceState")
                        .HasForeignKey("DAL.Entities.DeviceState", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DAL.Entities.DeviceStateHistory", b =>
                {
                    b.HasOne("DAL.Entities.Device", "Device")
                        .WithMany("History")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("DAL.Entities.Device", b =>
                {
                    b.Navigation("DeviceState");

                    b.Navigation("History");
                });

            modelBuilder.Entity("DAL.Entities.Room", b =>
                {
                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
